StoreCalls/Models/Call.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StoreCalls.Models
{
    public class Call
    {
        public long CallId { get; set; }

        [ForeignKey ("Category")]
        public long CategoryId { get; set; }

        [ForeignKey("Employee")]
        public long EmployeeId { get; set; }

        public string Program { get; set; }

        public string Comments { get; set; }

        public bool Positive { get; set; }

        public DateTime TimeCall { get; set; }

        public virtual Person Person { get; set; }

        public virtual Employee Employee { get; set; }

        public virtual Category Category { get; set; }

        public Call(long CategoryId, long EmployeeId, string program, string comments, bool positive, Person person)
        {
            this.CategoryId = CategoryId;
            this.EmployeeId = EmployeeId;
            this.Program = program;
            this.Comments = comments;
            this.Positive = positive;
            this.Person = person;
            this.TimeCall = DateTime.Now;
        }
        public Call() { }

        public Call(string program, string comments, bool positive)
        {
            this.Program = program;
            this.Comments = comments;
            this.Positive = positive;
        }

    }
}

StoreCalls/Controllers/CallController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreCalls.Models;
using StoreCalls.DAL;

namespace StoreCalls.Controllers
{
    public class CallController : Controller
    {
        private CallContext db = new CallContext();

        //
        // GET: /Call/
        [HttpGet]
        public ActionResult Index()
        {
            //var calls = db.Calls.Include(c => c.Employee).Include(c => c.Category);
            //return View(calls.ToList());
            var program = new SelectList(new[] { "Morning", "Afternoon" });
            List<SelectListItem> catDb = new List<SelectListItem>();
            var categories = db.Categories.Select(x => new SelectListItem() { Text = x.CategoryName, Value = x.CategoryName });
            foreach (var c in categories)
            {
                catDb.Add(new SelectListItem() { Text = c.Text, Value = c.Value });
            }
            
            //var categoriesList = new SelectList(new[] { "Sport", "Police" });

            SelectList tmp = new SelectList(catDb, "Value", "Text", null);
            ViewBag.ProgramList = program;
            ViewBag.CategoriesList = tmp;
            return View();
        }

        [HttpPost]
        public JsonResult Index(Models.Registration registration)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var aux = (from ca in db.Categories
                               where ca.CategoryName.Equals(registration.Categories)
                               select ca).Single();
                    Person person = new Person(registration.PhoneNumber, registration.Name, registration.LastName, registration.Address1, registration.Address2, registration.PostCode);
                    
                    
                    // Check if a person already exists on the table with that phone number.
                    var checkPerson = db.Persons.Any(p => p.PhoneNumber == person.PhoneNumber);
                    if (checkPerson)
                    {
                        Person tmpPerson = db.Persons.Single(p => p.PhoneNumber == person.PhoneNumber);

                        if (TryUpdateModel(tmpPerson, new string[] { "Name", "LastName", "Address1", "Address2", "PostCode" }))
                        {
                            try
                            {
                                db.Entry(tmpPerson).State = EntityState.Modified;
                                db.SaveChanges();
                                Call call = new Call(aux.CategoryId, 1, registration.Program, registration.Comments, registration.Positive, tmpPerson);
                                db.Calls.Add(call);
                                db.SaveChanges();
                            }
                            catch (DataException)
                            {
                                return Json(new { Comments = "error with the update" });
                            }
                        }
                        
                    }
                    else
                    {
                        Call call = new Call(aux.CategoryId, 1, registration.Program, registration.Comments, registration.Positive, person);
                        db.Calls.Add(call);
                        db.SaveChanges();
                    }


                    //employee.ForEach(s => context.Employees.AddOrUpdate(p => p.LastName, s));
                    //db.Calls.Add(call); //this works
                    //db.Calls.AddOrUpdate(c => c.comments);
                    


                    //db.SaveChanges();
                    
                    string message = string.Format("message '{0}'", registration.Comments);
                    registration.Comments = message;
                    //string message = string.Format("message '{0}'", call.Caller.Name);
                    return Json(registration);
                }
                catch (Exception e)
                {
                    throw e;
                }

            }
            string error = "error";
            return Json(error);
        }
        [HttpPost]
        public JsonResult Complete(Models.Registration registration)
        {
            var aux = db.Persons.Any(p => p.PhoneNumber == registration.PhoneNumber);
            if (aux)
            {
                Person tmpPerson = db.Persons.Single(p => p.PhoneNumber == registration.PhoneNumber);

                registration.Name = tmpPerson.Name;
                registration.LastName = tmpPerson.LastName;
                registration.Address1 = tmpPerson.Address1;
                registration.Address2 = tmpPerson.Address2;
                registration.PostCode = tmpPerson.PostCode;
                return Json(registration);
            }
            return Json(false);
        }

        [HttpPost]
        public JsonResult Historical(Models.Registration registration)
        {
            var aux = db.Persons.Any(p => p.PhoneNumber == registration.PhoneNumber);
            if (aux)
            {
                Person tmpPerson = db.Persons.Single(p => p.PhoneNumber == registration.PhoneNumber);

                var bCalls = db.Calls.Any(c => c.Person.PersonId == tmpPerson.PersonId);

                if (bCalls)
                {
                    var calls = (from ca in db.Calls
                                 where ca.Person.PersonId == tmpPerson.PersonId
                                 select ca);

                    List<Call> lCall = new List<Call>();
                    foreach (var c in calls)
                    {
                        Call call = new Call(c.Program, c.Comments, c.Positive);
                        lCall.Add(call);
                    }
                    //return this.Json(lCall);
                    return Json(new { Name = tmpPerson.Name, LastName = tmpPerson.LastName, Address1 = tmpPerson.Address1, Address2 = tmpPerson.Address2, PostCode = tmpPerson.PostCode, Calls = lCall });
                }
                else
                    return Json(false);
               
            }
            return Json(false);
        }


        //
        // GET: /Call/Details/5

        public ActionResult Details(long id = 0)
        {
            Call call = db.Calls.Find(id);
            if (call == null)
            {
                return HttpNotFound();
            }
            return View(call);
        }

        //
        // GET: /Call/Create

        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name");
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        //
        // POST: /Call/Create

        [HttpPost]
        public ActionResult Create(Call call)
        {
            if (ModelState.IsValid)
            {
                db.Calls.Add(call);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name", call.EmployeeId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", call.CategoryId);
            return View(call);
        }

        //
        // GET: /Call/Edit/5

        public ActionResult Edit(long id = 0)
        {
            Call call = db.Calls.Find(id);
            if (call == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name", call.EmployeeId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", call.CategoryId);
            return View(call);
        }

        //
        // POST: /Call/Edit/5

        [HttpPost]
        public ActionResult Edit(Call call)
        {
            if (ModelState.IsValid)
            {
                db.Entry(call).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name", call.EmployeeId);
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", call.CategoryId);
            return View(call);
        }

        //
        // GET: /Call/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Call call = db.Calls.Find(id);
            if (call == null)
            {
                return HttpNotFound();
            }
            return View(call);
        }

        //
        // POST: /Call/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Call call = db.Calls.Find(id);
            db.Calls.Remove(call);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

StoreCalls/Views/Call/Copy of Index.cshtml
@model StoreCalls.Models.Call

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>Registration of call</h2>
@using (Html.BeginForm("Index", "Call"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Person.PhoneNumber)
                @Html.TextBoxFor(m => m.Person.PhoneNumber)
            </li>
            <li>
                @Html.LabelFor(m => m.Person.Name)
                @Html.TextBoxFor(m => m.Person.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.Person.LastName)
                @Html.TextBoxFor(m => m.Person.LastName)
            </li>
            <li>
                @Html.LabelFor(m => m.Person.Address1)
                @Html.TextBoxFor(m => m.Person.Address1)
            </li>
            <li>
                @Html.LabelFor(m => m.Person.Address2)
                @Html.TextBoxFor(m => m.Person.Address2)
            </li>
            <li>
                @Html.LabelFor(m => m.Program)
                @Html.DropDownListFor(m => m.Program, (SelectList)ViewBag.ProgramList)
            </li>
            <li>
                @Html.LabelFor(m => m.Category)
                @Html.DropDownListFor(m => m.Category, (SelectList)ViewBag.CategoriesList)
            </li>
            <li>
                @Html.LabelFor(m => m.Comments)
                @Html.TextAreaFor(m => m.Comments)
            </li>
            <li>
                @Html.LabelFor(m => m.Positive)
                <input type="radio" name="commentPN" value="Positive" /> Positive
                <input type="radio" name="commentPN" value="Negative" /> Negative
            </li>
        </ol>
        <input class="register-call" type="submit" value="Register" />
    </fieldset>
    
    <div id="formS">

    </div>
    <br /><br /><br />
    <div id="formS2">
        
    </div>
}
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.register-call').on("click", function () {
                var form = $(this).parent("form");
                $('div#formS').text($("form").serialize());
                console.log("registration");
                $.ajax({
                    type: "POST",
                    url: form.attr('action'),
                    //url: "/call",
                    dataType: 'json',
                    ContentType: 'application/json',
                    //data: { Comments: $('textarea#Comments').val(), Caller_Name: $('input#Caller_Name').val(), Caller_LastName: $('input#Caller_LastName').val() }
                    //data: { comments: comments }
                    data: $("form").serialize()
                    //data: stringfied
                })
                    .success(function (data) {
                        console.log(data);
                        alert(data.Comments);
                    })
                    .error(function () {
                        alert("Your bid has been rejected");
                    });

                return false;
            });
        });
    </script>
}

StoreCalls/Views/Call/Create.cshtml
@model StoreCalls.Models.Call

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Call</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, "Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", String.Empty)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmployeeId, "Employee")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EmployeeId", String.Empty)
            @Html.ValidationMessageFor(model => model.EmployeeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Program)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Program)
            @Html.ValidationMessageFor(model => model.Program)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Positive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Positive)
            @Html.ValidationMessageFor(model => model.Positive)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreCalls/Views/Call/Delete.cshtml
@model StoreCalls.Models.Call

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Call</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category.CategoryName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.CategoryName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Employee.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Employee.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Program)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Program)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Positive)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Positive)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

StoreCalls/Views/Call/Details.cshtml
@model StoreCalls.Models.Call

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Call</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Category.CategoryName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Category.CategoryName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Employee.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Employee.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Program)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Program)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Comments)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Comments)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Positive)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Positive)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.CallId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoreCalls/Views/Call/Edit.cshtml
@model StoreCalls.Models.Call

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Call</legend>

        @Html.HiddenFor(model => model.CallId)

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId, "Category")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", String.Empty)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmployeeId, "Employee")
        </div>
        <div class="editor-field">
            @Html.DropDownList("EmployeeId", String.Empty)
            @Html.ValidationMessageFor(model => model.EmployeeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Program)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Program)
            @Html.ValidationMessageFor(model => model.Program)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Positive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Positive)
            @Html.ValidationMessageFor(model => model.Positive)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreCalls/Views/Call/Index.cshtml
@model StoreCalls.Models.Registration

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h2>Registration of call</h2>
@using (Html.BeginForm("Index", "Call"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.TextBoxFor(m => m.PhoneNumber)
            </li>
            <li>
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name)
            </li>
            <li>
                @Html.LabelFor(m => m.LastName)
                @Html.TextBoxFor(m => m.LastName)
            </li>
            <li>
                @Html.LabelFor(m => m.Address1)
                @Html.TextBoxFor(m => m.Address1)
            </li>
            <li>
                @Html.LabelFor(m => m.Address2)
                @Html.TextBoxFor(m => m.Address2)
            </li>
            <li>
                @Html.LabelFor(m => m.PostCode)
                @Html.TextBoxFor(m => m.PostCode)
            </li>
            <li>
                @Html.LabelFor(m => m.Program)
                @Html.DropDownListFor(m => m.Program, (SelectList)ViewBag.ProgramList)
            </li>
            <li>
                @Html.LabelFor(m => m.Categories)
                @Html.DropDownListFor(m => m.Categories, (SelectList)ViewBag.CategoriesList)
            </li>
            <li>
                @Html.LabelFor(m => m.Comments)
                @Html.TextAreaFor(m => m.Comments)
            </li>
            <li>
                @Html.LabelFor(m => m.Positive)
                @Html.RadioButtonFor(m => m.Positive, true) Positive
                @Html.RadioButtonFor(m => m.Positive, false) Negative
            </li>
        </ol>
        <input class="register-call" type="submit" value="Register" />
    </fieldset>
    
    <div id="formS">

    </div>
    <br /><br /><br />
    <div id="formS2">
        
    </div>
}